[build]
builder = "NIXPACKS"
buildCommand = "cd backend && rm -rf dist node_modules package-lock.json && npm install && npm run build"

[deploy]
startCommand = "cd backend && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
